(require :asdf)
(push (truename (merge-pathnames "../" (directory-namestring *load-truename*))) asdf:*central-registry*)
(handler-bind ((warning #'muffle-warning)) (asdf:load-system "shuttle"))
(in-package #:shuttle)
(load (merge-pathnames "test262-lib.lisp" (directory-namestring *load-truename*)))
(let* ((rel (sb-ext:posix-getenv "T"))
       (path (merge-pathnames rel (merge-pathnames "test/" *root*)))
       (src (slurp path)) (fm (frontmatter src)))
  (handler-case
      (let ((realm (make-realm)))
        (unless (fm-flag fm "raw")
          (run-code *default-harness* realm)
          (dolist (inc (fm-list fm "includes")) (run-code (include-code inc) realm)))
        (run-code (compile-toplevel src) realm)
        (format t "~&OK~%"))
    (shuttle-error (e)
      (let ((v (shuttle-error-value e)))
        (format t "~&THREW: ~a || msg=~a~%"
                (ignore-errors (to-string v))
                (ignore-errors (and (js-object-p v) (to-string (js-get v "message")))))))
    (error (e) (format t "~&LISP-ERR: ~a~%" e)))
  (ignore-errors (terminate-all-generators))
  (sb-ext:exit :code 0))
