;;;; semver-gate.lisp — grade shuttle's semver against the one npm actually resolves with.
;;;;
;;;; The corpus in inspect/semver-cases.tsv was generated by inspect/gen-semver-cases.js from the
;;;; `semver` package bundled with npm.  Capturing it means this gate needs neither node nor the
;;;; network, and that the expectations cannot drift underneath a passing run.
;;;;
;;;;   sbcl --script inspect/semver-gate.lisp

(require :asdf)
(push (truename (merge-pathnames "../" (directory-namestring *load-truename*)))
      asdf:*central-registry*)
(handler-bind ((warning #'muffle-warning))
  (let ((*standard-output* (make-broadcast-stream))) (asdf:load-system "shuttle/semver")))
(in-package #:shuttle)

(defvar *n* 0) (defvar *bad* 0) (defvar *shown* 0)
(defvar *candidates* '())
(defun grade (kind a b want got)
  (incf *n*)
  (unless (equal want got)
    (incf *bad*)
    (when (< *shown* 25)
      (incf *shown*)
      (format t "  ~a  ~s ~s~%      want ~s   got ~s~%" kind a b want got))))

(let ((path (merge-pathnames "semver-cases.tsv" (directory-namestring *load-truename*)))
      (by-kind (make-hash-table :test 'equal)))
  (with-open-file (s path :external-format :utf-8)
    (loop for line = (read-line s nil) while line
          do (let* ((f (let ((acc '()) (start 0))
                         (loop for p = (position #\Tab line :start start)
                               do (push (subseq line start p) acc)
                               while p do (setf start (1+ p)))
                         (nreverse acc)))
                    (kind (first f)))
               (incf (gethash kind by-kind 0))
               (cond
                 ((string= kind "VALID")
                  (grade kind (second f) nil (string= (third f) "true")
                         (and (parse-semver (second f)) t)))
                 ((string= kind "CMP")
                  (grade kind (second f) (third f) (parse-integer (fourth f))
                         (semver-compare (parse-semver (second f)) (parse-semver (third f)))))
                 ((string= kind "SAT")
                  (grade kind (second f) (third f) (string= (fourth f) "true")
                         (and (semver-satisfies-p (third f) (second f)) t)))
                 ((string= kind "VALIDRANGE")
                  (grade kind (second f) nil (string= (third f) "true")
                         (and (parse-range (second f)) t)))
                 ((string= kind "VERSIONS")
                  (setf *candidates* (remove "" (%split (second f) #\,) :test #'string=)))
                 ((string= kind "MAXSAT")
                  (let ((got (semver-max-satisfying *candidates* (second f))))
                    (grade kind (second f) nil (third f)
                           (if got (semver-string got) "-"))))))))
  (format t "~&~%cases by kind:~{ ~a~}~%"
          (let (acc) (maphash (lambda (k v) (push (format nil "~a=~d" k v) acc)) by-kind) acc))
  (format t "semver gate: ~d cases, ~d disagreements with npm's semver~%" *n* *bad*)
  (sb-ext:exit :code (if (zerop *bad*) 0 1)))
