;;;; vm.lisp — the stack VM, environments, operator semantics, and the
;;;; function/closure machinery. JS functions and host (CL-backed) functions
;;;; both present as objects with [[Call]] — the seam weft calls across.
(in-package #:shuttle)

(defstruct (realm (:constructor %make-realm)) object-proto function-proto array-proto global global-env)
(defvar *current-realm*)
(defun %obj-proto () (realm-object-proto *current-realm*))
(defun %fn-proto () (realm-function-proto *current-realm*))
(defun %arr-proto () (realm-array-proto *current-realm*))

;;; ---- environments ----
(defstruct env vars parent)
(defun new-env (parent) (make-env :vars (make-hash-table :test 'equal) :parent parent))
(defun env-root (e) (loop while (env-parent e) do (setf e (env-parent e))) e)
(defun env-get (env name)
  (loop for e = env then (env-parent e) while e
        do (multiple-value-bind (v p) (gethash name (env-vars e)) (when p (return-from env-get v))))
  *undefined*)
(defun env-set (env name val)
  (loop for e = env then (env-parent e) while e
        do (when (nth-value 1 (gethash name (env-vars e)))
             (setf (gethash name (env-vars e)) val) (return-from env-set val)))
  (setf (gethash name (env-vars (env-root env))) val) val)              ; sloppy implicit global
(defun env-declare (env name val) (setf (gethash name (env-vars env)) val))

;;; ---- object builders ----
(defun make-array-object (elems)
  (let ((o (make-object :proto (%arr-proto) :class "Array")))
    (loop for e in elems for i from 0 do (put o (princ-to-string i) e))
    (put o "length" (float (length elems) 1d0)) o))
(defun make-plain-object (pairs)
  (let ((o (make-object :proto (%obj-proto))))
    (loop for (k . v) in pairs do (put o (if (stringp k) k (to-string k)) v)) o))

(defun make-js-function (code env)
  (let ((fn (make-object :proto (%fn-proto) :class "Function")))
    (put fn "length" (float (length (code-params code)) 1d0) :enumerable nil :writable nil)
    (when (code-name code) (put fn "name" (code-name code) :enumerable nil :writable nil))
    (setf (js-object-call fn)
          (lambda (this args)
            (let ((fenv (new-env env)))
              (loop for p in (code-params code) for rest = args then (cdr rest)
                    do (env-declare fenv p (if rest (car rest) *undefined*)))
              (run code fenv this))))
    (setf (js-object-construct fn)
          (lambda (args new-target) (declare (ignore new-target))
            (let* ((pp (js-get fn "prototype"))
                   (obj (make-object :proto (if (js-object-p pp) pp (%obj-proto)))))
              (let ((r (funcall (js-object-call fn) obj args))) (if (js-object-p r) r obj)))))
    ;; a fresh .prototype so `new` works and methods can be attached
    (let ((proto (make-object :proto (%obj-proto)))) (put proto "constructor" fn :enumerable nil)
      (put fn "prototype" proto :enumerable nil))
    fn))

;;; ---- operators ----
(defun to-int32 (v)
  (let ((n (to-number v)))
    (if (or (js-nan-p n) (= n *inf*) (= n *-inf*)) 0
        (let ((m (mod (truncate n) #x100000000))) (if (>= m #x80000000) (- m #x100000000) m)))))

(defun js-mod (a b)
  (with-js-floats
    (let ((x (to-number a)) (y (to-number b)))
      (cond ((or (js-nan-p x) (js-nan-p y) (zerop y) (= (abs x) *inf*)) *nan*)
            ((= (abs y) *inf*) x) ((zerop x) x) (t (rem x y))))))

(defun js-relational (op a b)
  (let ((pa (to-primitive a :number)) (pb (to-primitive b :number)))
    (if (and (stringp pa) (stringp pb))
        (js-bool (funcall (cond ((string= op "<") #'string<) ((string= op ">") #'string>)
                                ((string= op "<=") #'string<=) (t #'string>=)) pa pb))
        (let ((x (to-number pa)) (y (to-number pb)))
          (if (or (js-nan-p x) (js-nan-p y)) *false*
              (js-bool (funcall (cond ((string= op "<") #'<) ((string= op ">") #'>)
                                      ((string= op "<=") #'<=) (t #'>=)) x y)))))))

(defun js-binop (op a b)
  (cond ((string= op "+") (js-add a b))
        ((string= op "-") (with-js-floats (- (to-number a) (to-number b))))
        ((string= op "*") (with-js-floats (* (to-number a) (to-number b))))
        ((string= op "/") (with-js-floats (/ (to-number a) (to-number b))))
        ((string= op "%") (js-mod a b))
        ((string= op "===") (js-bool (js-strict-equal a b)))
        ((string= op "!==") (js-bool (not (js-strict-equal a b))))
        ((string= op "==") (js-bool (js-equal a b)))
        ((string= op "!=") (js-bool (not (js-equal a b))))
        ((member op '("<" ">" "<=" ">=") :test #'string=) (js-relational op a b))
        ((string= op "&") (float (logand (to-int32 a) (to-int32 b)) 1d0))
        ((string= op "|") (float (logior (to-int32 a) (to-int32 b)) 1d0))
        ((string= op "^") (float (logxor (to-int32 a) (to-int32 b)) 1d0))
        (t (js-throw (format nil "operator ~a not supported" op)))))

(defun js-unop (op v)
  (cond ((string= op "!") (js-bool (not (js-truthy v))))
        ((string= op "-") (with-js-floats (- (to-number v))))
        ((string= op "+") (to-number v))
        ((string= op "~") (float (lognot (to-int32 v)) 1d0))
        ((string= op "typeof") (js-typeof v))
        (t (js-throw (format nil "unary ~a not supported" op)))))

;;; ---- the VM ----
(defun run (code env this)
  (let ((instrs (code-instrs code)) (pc 0)
        (stack (make-array 64 :adjustable t :fill-pointer 0)) (completion *undefined*))
    (macrolet ((push! (v) `(vector-push-extend ,v stack))
               (pop! () `(vector-pop stack))
               (peek! () `(aref stack (1- (fill-pointer stack)))))
      (loop
        (when (>= pc (length instrs)) (return completion))
        (let* ((in (aref instrs pc)) (op (car in)) (a (cdr in)))
          (incf pc)
          (case op
            (:const (push! (first a)))
            (:get-var (push! (env-get env (first a))))
            (:set-var (env-set env (first a) (peek!)))
            (:declare-var (env-declare env (first a) (pop!)))
            (:get-this (push! this))
            (:pop (pop!))
            (:dup (push! (peek!)))
            (:to-num (push! (to-number (pop!))))
            (:save-completion (setf completion (pop!)))
            (:bin (let ((b (pop!)) (x (pop!))) (push! (js-binop (first a) x b))))
            (:unary (push! (js-unop (first a) (pop!))))
            (:get-prop (let ((k (pop!)) (o (pop!))) (push! (js-get o k))))
            (:get-prop-c (push! (js-get (pop!) (first a))))
            (:set-prop (let ((v (pop!)) (k (pop!)) (o (pop!))) (js-set o k v) (push! v)))
            (:call (let* ((args (loop repeat (first a) collect (pop!)))
                          (callee (pop!)) (thisv (pop!)))
                     (push! (js-call callee thisv (nreverse args)))))
            (:new (let* ((args (loop repeat (first a) collect (pop!))) (callee (pop!)))
                    (push! (js-construct callee (nreverse args)))))
            (:closure (push! (make-js-function (first a) env)))
            (:array (push! (make-array-object (nreverse (loop repeat (first a) collect (pop!))))))
            (:object (push! (make-plain-object
                             (nreverse (loop repeat (first a) collect (let ((v (pop!)) (k (pop!))) (cons k v)))))))
            (:jmp (setf pc (first a)))
            (:jmp-if-false (unless (js-truthy (pop!)) (setf pc (first a))))
            (:jmp-if-true (when (js-truthy (pop!)) (setf pc (first a))))
            (:and-jmp (if (js-truthy (peek!)) (pop!) (setf pc (first a))))
            (:or-jmp (if (js-truthy (peek!)) (setf pc (first a)) (pop!)))
            (:ret (return (pop!)))
            (:throw-op (js-throw (pop!)))
            (t (error "shuttle vm: bad op ~a" op))))))))
