;;;; vm.lisp — the stack VM, environments, operator semantics, and the
;;;; function/closure machinery. JS functions and host (CL-backed) functions
;;;; both present as objects with [[Call]] — the seam weft calls across.
(in-package #:shuttle)

(defstruct (realm (:constructor %make-realm))
  object-proto function-proto array-proto
  string-proto number-proto boolean-proto symbol-proto
  symbol-registry                       ; string -> js-symbol (Symbol.for/keyFor)
  intrinsics                            ; plist: keyword -> js object (constructors etc.)
  global global-env)
(defvar *current-realm*)
(defun %obj-proto () (realm-object-proto *current-realm*))
(defun %fn-proto () (realm-function-proto *current-realm*))
(defun %arr-proto () (realm-array-proto *current-realm*))
(defun %intrinsic (key) (getf (realm-intrinsics *current-realm*) key))

;;; ---- ToObject: box a primitive into its wrapper object ----
(defun box-primitive (v)
  (let ((r *current-realm*))
    (cond
      ((stringp v)
       (let ((o (make-object :proto (realm-string-proto r) :class "String")))
         (setf (js-object-primitive o) v)
         (put o "length" (float (length v) 1d0) :enumerable nil :writable nil :configurable nil)
         o))
      ((floatp v)
       (let ((o (make-object :proto (realm-number-proto r) :class "Number")))
         (setf (js-object-primitive o) v) o))
      ((or (eq v *true*) (eq v *false*))
       (let ((o (make-object :proto (realm-boolean-proto r) :class "Boolean")))
         (setf (js-object-primitive o) v) o))
      ((js-symbol-p v)
       (let ((o (make-object :proto (realm-symbol-proto r) :class "Symbol")))
         (setf (js-object-primitive o) v) o))
      (t (js-throw "Cannot box value")))))

;;; ---- environments ----
(defstruct env vars parent)
(defun new-env (parent) (make-env :vars (make-hash-table :test 'equal) :parent parent))
(defun env-root (e) (loop while (env-parent e) do (setf e (env-parent e))) e)
(defun env-get (env name)
  "Return (values VALUE BOUND-P). BOUND-P nil means the name is not declared."
  (loop for e = env then (env-parent e) while e
        do (multiple-value-bind (v p) (gethash name (env-vars e)) (when p (return-from env-get (values v t)))))
  (values *undefined* nil))
(defun env-get-checked (env name)
  "Read a binding, throwing ReferenceError if the name is not declared."
  (multiple-value-bind (v p) (env-get env name)
    (if p v (js-throw (make-native-error "ReferenceError" (format nil "~a is not defined" name))))))
(defun env-typeof (env name)
  (multiple-value-bind (v p) (env-get env name) (if p (js-typeof v) "undefined")))
(defun env-set (env name val)
  (loop for e = env then (env-parent e) while e
        do (when (nth-value 1 (gethash name (env-vars e)))
             (setf (gethash name (env-vars e)) val) (return-from env-set val)))
  (setf (gethash name (env-vars (env-root env))) val) val)              ; sloppy implicit global
(defun env-declare (env name val) (setf (gethash name (env-vars env)) val))

;;; ---- object builders ----
(defun make-array-object (elems)
  (let ((o (make-object :proto (%arr-proto) :class "Array")))
    (loop for e in elems for i from 0 do (put o (princ-to-string i) e))
    (put o "length" (float (length elems) 1d0)) o))
(defun make-plain-object (pairs)
  (let ((o (make-object :proto (%obj-proto))))
    (loop for (k . v) in pairs do (put o (if (stringp k) k (to-string k)) v)) o))

(defun array-object-to-list (arr)
  "Read a dense array object's indexed elements 0..length-1 into a CL list."
  (let ((n (truncate (to-number (js-get arr "length")))))
    (loop for i from 0 below n collect (js-get arr (princ-to-string i)))))

(defun object-rest-copy (src taken)
  "Copy own enumerable string keys of SRC into a fresh object, excluding TAKEN."
  (let ((o (make-object :proto (%obj-proto))) (src (to-object src)))
    (when (js-object-p src)
      (dolist (k (js-own-keys src))
        (when (and (stringp k) (not (member k taken :test #'string=)))
          (let ((d (js-get-own-property src k)))
            (when (and d (prop-enumerable d))
              (put o k (js-get src k)))))))
    o))

(defun for-in-key-array (o)
  "Array of enumerable string keys of O and its prototype chain (deduped)."
  (if (js-object-p o)
      (let ((seen (make-hash-table :test 'equal)) (out '()))
        (loop for cur = o then (js-object-proto cur)
              while (js-object-p cur)
              do (dolist (k (js-own-keys cur))
                   (when (and (stringp k) (not (gethash k seen)))
                     (setf (gethash k seen) t)
                     (let ((d (js-get-own-property cur k)))
                       (when (and d (prop-enumerable d)) (push k out))))))
        (make-array-object (nreverse out)))
      (make-array-object '())))

;;; ---- iterator protocol (for-of, spread, Array.from) ----
(defvar *symbol-iterator* nil)          ; @@iterator well-known symbol (set at realm build)
(defun get-iterator (obj)
  (let ((o (to-object obj)))
    (let ((itf (and *symbol-iterator* (js-get o *symbol-iterator*))))
      (unless (js-callable-p itf)
        (js-throw (make-native-error "TypeError" (format nil "~a is not iterable" (ignore-errors (to-string obj))))))
      (let ((it (js-call itf o '())))
        (unless (js-object-p it) (js-throw (make-native-error "TypeError" "iterator is not an object")))
        it))))
(defun iterator-step (it)
  "Call it.next(); return the result record ({value,done})."
  (let ((next (js-get it "next")))
    (unless (js-callable-p next) (js-throw (make-native-error "TypeError" "iterator.next is not a function")))
    (let ((r (js-call next it '())))
      (unless (js-object-p r) (js-throw (make-native-error "TypeError" "iterator result is not an object")))
      r)))

(defun make-arguments-object (args)
  "A minimal (unmapped) arguments object: indexed elements + length + @@iterator."
  (let ((o (make-object :proto (%obj-proto) :class "Arguments")))
    (loop for a in args for i from 0 do (put o (princ-to-string i) a))
    (put o "length" (float (length args) 1d0) :enumerable nil)
    (when *symbol-iterator*
      (let ((av (realm-array-proto *current-realm*)))
        (put o *symbol-iterator* (js-get av *symbol-iterator*) :enumerable nil)))
    o))

(defun make-js-function (code env)
  (let ((fn (make-object :proto (%fn-proto) :class "Function")))
    (put fn "length" (float (length (code-params code)) 1d0) :enumerable nil :writable nil)
    (when (code-name code) (put fn "name" (code-name code) :enumerable nil :writable nil))
    (setf (js-object-call fn)
          (lambda (this args)
            (let ((fenv (new-env env)))
              (env-declare fenv "arguments" (make-arguments-object args))
              (run code fenv this args))))
    (setf (js-object-construct fn)
          (lambda (args new-target) (declare (ignore new-target))
            (let* ((pp (js-get fn "prototype"))
                   (obj (make-object :proto (if (js-object-p pp) pp (%obj-proto)))))
              (let ((r (funcall (js-object-call fn) obj args))) (if (js-object-p r) r obj)))))
    ;; a fresh .prototype so `new` works and methods can be attached
    (let ((proto (make-object :proto (%obj-proto)))) (put proto "constructor" fn :enumerable nil)
      (put fn "prototype" proto :enumerable nil))
    fn))

;;; ---- operators ----
(defun to-int32 (v)
  (let ((n (to-number v)))
    (if (or (js-nan-p n) (= n *inf*) (= n *-inf*)) 0
        (let ((m (mod (truncate n) #x100000000))) (if (>= m #x80000000) (- m #x100000000) m)))))

(defun js-mod (a b)
  (with-js-floats
    (let ((x (to-number a)) (y (to-number b)))
      (cond ((or (js-nan-p x) (js-nan-p y) (zerop y) (= (abs x) *inf*)) *nan*)
            ((= (abs y) *inf*) x) ((zerop x) x) (t (rem x y))))))

(defun js-relational (op a b)
  (let ((pa (to-primitive a :number)) (pb (to-primitive b :number)))
    (if (and (stringp pa) (stringp pb))
        (js-bool (funcall (cond ((string= op "<") #'string<) ((string= op ">") #'string>)
                                ((string= op "<=") #'string<=) (t #'string>=)) pa pb))
        (let ((x (to-number pa)) (y (to-number pb)))
          (if (or (js-nan-p x) (js-nan-p y)) *false*
              (js-bool (funcall (cond ((string= op "<") #'<) ((string= op ">") #'>)
                                      ((string= op "<=") #'<=) (t #'>=)) x y)))))))

(defun js-binop (op a b)
  (cond ((string= op "+") (js-add a b))
        ((string= op "-") (with-js-floats (- (to-number a) (to-number b))))
        ((string= op "*") (with-js-floats (* (to-number a) (to-number b))))
        ((string= op "/") (with-js-floats (/ (to-number a) (to-number b))))
        ((string= op "%") (js-mod a b))
        ((string= op "**") (with-js-floats (js-pow (to-number a) (to-number b))))
        ((string= op "<<") (let ((m (mod (logand (to-int32 a) #xFFFFFFFF) #x100000000))
                                 (s (logand (to-int32 b) 31)))
                             (let ((r (mod (ash m s) #x100000000)))
                               (float (if (>= r #x80000000) (- r #x100000000) r) 1d0))))
        ((string= op ">>") (float (ash (to-int32 a) (- (logand (to-int32 b) 31))) 1d0))
        ((string= op ">>>") (float (ash (to-uint32 a) (- (logand (to-int32 b) 31))) 1d0))
        ((string= op "===") (js-bool (js-strict-equal a b)))
        ((string= op "!==") (js-bool (not (js-strict-equal a b))))
        ((string= op "==") (js-bool (js-equal a b)))
        ((string= op "!=") (js-bool (not (js-equal a b))))
        ((member op '("<" ">" "<=" ">=") :test #'string=) (js-relational op a b))
        ((string= op "&") (float (logand (to-int32 a) (to-int32 b)) 1d0))
        ((string= op "|") (float (logior (to-int32 a) (to-int32 b)) 1d0))
        ((string= op "^") (float (logxor (to-int32 a) (to-int32 b)) 1d0))
        ((string= op "instanceof") (js-bool (js-instanceof a b)))
        ((string= op "in") (js-bool (and (js-object-p b) (js-has b (prop-key a)))))
        (t (js-throw (format nil "operator ~a not supported" op)))))

(defun js-instanceof (a b)
  (unless (js-callable-p b) (js-throw "Right-hand side of 'instanceof' is not callable"))
  (let ((proto (js-get b "prototype")))
    (and (js-object-p a)
         (loop for p = (js-object-proto a) then (js-object-proto p)
               while (js-object-p p) thereis (eq p proto)))))

(defun js-unop (op v)
  (cond ((string= op "!") (js-bool (not (js-truthy v))))
        ((string= op "-") (with-js-floats (- (to-number v))))
        ((string= op "+") (to-number v))
        ((string= op "~") (float (lognot (to-int32 v)) 1d0))
        ((string= op "void") *undefined*)
        ((string= op "typeof") (js-typeof v))
        (t (js-throw (format nil "unary ~a not supported" op)))))

;;; ---- the VM ----
(define-condition shuttle-timeout (error) ()   ; distinct from a JS throw
  (:report (lambda (c s) (declare (ignore c)) (format s "shuttle: instruction budget exceeded"))))
(declaim (type fixnum *steps* *max-steps*))
(defparameter *steps* 0) (defparameter *max-steps* 2000000)   ; per-run budget (guards infinite loops)

(defun run (code env this &optional call-args)
  (let ((instrs (code-instrs code)) (pc 0)
        (call-args (coerce call-args 'vector))
        (stack (make-array 64 :adjustable t :fill-pointer 0)) (completion *undefined*)
        (handlers '()))                      ; ((catch-pc . saved-sp) ...) for try/catch
    (macrolet ((push! (v) `(vector-push-extend ,v stack))
               (pop! () `(vector-pop stack))
               (peek! () `(aref stack (1- (fill-pointer stack)))))
      (loop
       (handler-case
        (loop
        (when (>= pc (length instrs)) (return-from run completion))
        (when (>= (incf *steps*) *max-steps*) (error 'shuttle-timeout))
        (let* ((in (aref instrs pc)) (op (car in)) (a (cdr in)))
          (incf pc)
          (case op
            (:push-handler (push (cons (first a) (fill-pointer stack)) handlers))
            (:pop-handler (pop handlers))
            (:const (push! (first a)))
            (:get-var (push! (env-get-checked env (first a))))
            (:typeof-var (push! (env-typeof env (first a))))
            (:set-var (env-set env (first a) (peek!)))
            (:declare-var (env-declare env (first a) (pop!)))
            (:get-this (push! this))
            (:load-arg (let ((n (first a))) (push! (if (< n (length call-args)) (aref call-args n) *undefined*))))
            (:load-rest (let ((n (first a)))
                          (push! (make-array-object
                                  (loop for i from n below (length call-args) collect (aref call-args i))))))
            (:pop (pop!))
            (:dup (push! (peek!)))
            (:dup2 (let ((b (peek!)) (n (fill-pointer stack)))
                     (declare (ignore b))
                     (let ((x (aref stack (- n 2))) (y (aref stack (- n 1))))
                       (push! x) (push! y))))
            (:to-num (push! (to-number (pop!))))
            (:to-str (push! (to-string (pop!))))
            (:swap (let ((n (fill-pointer stack)))
                     (rotatef (aref stack (- n 1)) (aref stack (- n 2)))))
            (:rot3 (let ((n (fill-pointer stack)))   ; [a b c] -> [b c a]
                     (let ((a (aref stack (- n 3))))
                       (setf (aref stack (- n 3)) (aref stack (- n 2))
                             (aref stack (- n 2)) (aref stack (- n 1))
                             (aref stack (- n 1)) a))))
            (:nullish-short (let ((v (peek!)))   ; if top is null/undefined, jump to SHORT (leave it)
                              (when (or (eq v *null*) (eq v *undefined*)) (setf pc (first a)))))
            (:save-completion (setf completion (pop!)))
            (:bin (let ((b (pop!)) (x (pop!))) (push! (js-binop (first a) x b))))
            (:unary (push! (js-unop (first a) (pop!))))
            (:get-prop (let ((k (pop!)) (o (pop!))) (push! (js-get o k))))
            (:get-prop-c (push! (js-get (pop!) (first a))))
            (:set-prop (let ((v (pop!)) (k (pop!)) (o (pop!))) (js-set o k v) (push! v)))
            (:del-prop (let ((k (pop!)) (o (pop!)))
                         (push! (if (js-object-p o) (js-delete o k) *true*))))
            (:update-prop (let* ((delta (first a)) (prefix (second a))
                                 (k (pop!)) (o (pop!))
                                 (old (to-number (js-get o k)))
                                 (new (with-js-floats (+ old delta))))
                            (js-set o k new)
                            (push! (if prefix new old))))
            (:for-in-keys (push! (for-in-key-array (pop!))))
            (:get-iterator (push! (get-iterator (pop!))))
            (:iter-next (push! (iterator-step (pop!))))
            (:iter-rest (let ((it (pop!)) (out '()))
                          (loop (let ((r (iterator-step it)))
                                  (when (js-truthy (js-get r "done")) (return))
                                  (push (js-get r "value") out)))
                          (push! (make-array-object (nreverse out)))))
            (:object-rest (let ((src (pop!)) (taken (first a)))
                            (push! (object-rest-copy src taken))))
            (:call (let* ((args (loop repeat (first a) collect (pop!)))
                          (callee (pop!)) (thisv (pop!)))
                     (push! (js-call callee thisv (nreverse args)))))
            (:new (let* ((args (loop repeat (first a) collect (pop!))) (callee (pop!)))
                    (push! (js-construct callee (nreverse args)))))
            (:call-spread (let* ((argsarr (pop!)) (callee (pop!)) (thisv (pop!)))
                            (push! (js-call callee thisv (array-object-to-list argsarr)))))
            (:new-spread (let* ((argsarr (pop!)) (callee (pop!)))
                           (push! (js-construct callee (array-object-to-list argsarr)))))
            (:closure (push! (make-js-function (first a) env)))
            (:array (push! (make-array-object (nreverse (loop repeat (first a) collect (pop!))))))
            (:object (push! (make-plain-object
                             (nreverse (loop repeat (first a) collect (let ((v (pop!)) (k (pop!))) (cons k v)))))))
            (:new-object (push! (make-object :proto (%obj-proto))))
            (:new-array (push! (make-array-object '())))
            (:def-prop (let ((v (pop!)) (k (pop!)))     ; obj key val -> obj
                         (js-define-own-property (peek!) (prop-key k)
                           (list :value v :writable t :enumerable t :configurable t))))
            (:def-getter (let ((fn (pop!)) (k (pop!)))  ; obj key fn -> obj
                           (js-define-own-property (peek!) (prop-key k)
                             (list :get fn :accessor t :enumerable t :configurable t))))
            (:def-setter (let ((fn (pop!)) (k (pop!)))
                           (js-define-own-property (peek!) (prop-key k)
                             (list :set fn :accessor t :enumerable t :configurable t))))
            (:set-proto (let ((pv (pop!)))              ; obj protoval -> obj
                          (when (or (js-object-p pv) (eq pv *null*))
                            (setf (js-object-proto (peek!)) pv))))
            (:def-spread (let ((src (pop!)))            ; obj src -> obj (copy own enumerable)
                           (let ((dst (peek!)))
                             (when (or (js-object-p src) (stringp src))
                               (let ((so (to-object src)))
                                 (dolist (k (js-own-keys so))
                                   (let ((d (js-get-own-property so k)))
                                     (when (and d (prop-enumerable d))
                                       (js-set dst k (js-get so k))))))))))
            (:array-spread (let ((iterable (pop!)) (idx (pop!)) (arr (peek!)))  ; arr idx iterable -> newidx
                             (let ((i (truncate (to-number idx))) (it (get-iterator iterable)))
                               (loop (let ((r (iterator-step it)))
                                       (when (js-truthy (js-get r "done")) (return))
                                       (js-set arr (princ-to-string i) (js-get r "value")) (incf i)))
                               (push! (float i 1d0)))))
            (:jmp (setf pc (first a)))
            (:jmp-if-false (unless (js-truthy (pop!)) (setf pc (first a))))
            (:jmp-if-true (when (js-truthy (pop!)) (setf pc (first a))))
            (:and-jmp (if (js-truthy (peek!)) (pop!) (setf pc (first a))))
            (:or-jmp (if (js-truthy (peek!)) (setf pc (first a)) (pop!)))
            (:nullish-jmp (let ((v (peek!)))    ; keep LHS if non-nullish, else eval RHS
                            (if (or (eq v *null*) (eq v *undefined*)) (pop!) (setf pc (first a)))))
            (:ret (return-from run (pop!)))
            (:throw-op (js-throw (pop!)))
            (t (error "shuttle vm: bad op ~a" op)))))
        (shuttle-error (e)
          (if handlers
              (destructuring-bind (catch-pc . saved-sp) (pop handlers)
                (setf (fill-pointer stack) saved-sp pc catch-pc)
                (vector-push-extend (shuttle-error-value e) stack))   ; thrown value -> catch param
              (error e))))))))
